prof_image: /assets/images/nopush/default.png
default_image: /assets/images/nopush/default.png

sass:
  style: expanded

show_drafts: true
future: true
unpublished: true

liquid:
  # strict_variables: true
  strict_filters: true

kramdown:
  show_warnings: true
