# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# 信息
title: amero_zZ
author: amero
description: >-
  amero的个人网站。
twitter_username: amero_zZ
github_username:  AmeroHan
repo_file_url: https://github.com/AmeroHan/AmeroHan.github.io/blob/main/
lang: zh-CN
prof_image: https://s2.loli.net/2023/05/01/p3yAQuOvtqgo7lI.png

# 设置
timezone: Asia/Shanghai
permalink: /:year/:title
url: https://amero.moe
date_format: "%F"

# kramdown:
#   parse_block_html: true

# 分页
# paginate: 15
# paginate_path: "/blog/page:num/"

show_excerpts: true

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
#   - jekyll-paginate
#   - jekyll-sitemap

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - CNAME
  - serve locally.bat

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
