# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# 信息
title: amero_zZ
author: amero
description: >-
  amero的个人网站。
twitter_username: amero_zZ
github_username:  AmeroHan
repo_file_url: https://github.com/AmeroHan/AmeroHan.github.io/blob/main/
lang: zh-CN

# 设置
timezone: Asia/Shanghai
permalink: /:categories/:year/:title
url: https://amero.moe

# kramdown:
#   parse_block_html: true

## 分页
# paginate: 15
# paginate_path: "/blog/page:num/"

theme: minima
show_excerpts: true
minima:
  date_format: "%F"

# sass:
#   style: compressed

# plugins:
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
